### ISSUE TITLE
AKK FX3 Ultimate FCC Power Levels Seem Incorrect

### ISSUE THREAD

**Issue by ZzyzxTek** [Jackjan4/betaflight-vtx-tables#10]
For betaflight-vtx-tables/tables/akk/akk-fx3-ultimate-fcc.json

When I reference the AKK page for this VTX at: https://www.akktek.com/akk-fx3-ultimate-286.html 
as well as the docs included with the VTX (attached),
![AKK FX3-Ultimate VTX - Manual full](https://user-images.githubusercontent.com/26205931/87885022-6c3f8b00-c9c7-11ea-8e78-917389def625.jpg)

The power levels in the VTX table json seem incorrect.

The existing file has:

        "powerlevels_list": [
            {
                "value": 0,
                "label": "25"
            },
            {
                "value": 1,
                "label": "200"
            },
            {
                "value": 2,
                "label": "600"
            },
            {
                "value": 3,
                "label": "1W"
            }
        ]

I believe it should be:

        "powerlevels_list": [
            {
                "value": 0,
                "label": "25"
            },
            {
                "value": 1,
                "label": "200"
            },
            {
                "value": 2,
                "label": "400"
            },
            {
                "value": 3,
                "label": "600"
            }
        ]

I have this VTX, and the corrected power values seems to work as expected, however I do not have the equipment to measure the actual output power to verify if it is 25/200/400/600. I'm assuming the published AKK docs are correct.

The description in the file should also probably be updated to read (it seems to have a copy/paste description from the X2, which may be where the power levels and FCC vs international discrepancies came from as well):

    "description": "Betaflight VTX Config file for AKK FX3 Ultimate FCC version",

Also, it does not seem as though there is an international and FCC version of this VTX. Perhaps there was when it first came out? The current AKK site does not list two versions of this VTX. My notes from when I originally purchased this VTX (at the time it was released) do not mention a higher power version available, normally I would have noted that.

Perhaps I am mistaken with these power levels? Please advise.

**Comment by Jackjan4** [comment]
Powerlevels are now fixed.

You are right, there is no FCC version on the market. FCC in our context just means that our table is adapted to fit the FCC rules. This means that some frequencies are disabled in the E band to be legaly usable in the FCC countries.
