### ISSUE TITLE
Eachine wizard x220s vtx

### ISSUE THREAD

**Issue by rayb106** [Jackjan4/betaflight-vtx-tables#14]
Hi All,

I'm having problems trying to get my vtx unlocked, on the back of the vtx is a number (xf5804) I've got the vtx wired to a mamba black f405 mk2 see pic attached.  ![image](https://user-images.githubusercontent.com/85273394/127240234-e9455581-4d5f-4d64-9d34-e36a5225a9fe.jpeg) it's set as tramp audio, I've tried to copy some cli commands from got hub but when I plug into betaflight (latest ver) and have the battery connect my vtx still says device not ready can any one help ?

**Comment by Jackjan4** [comment]
Closed due to inactivity on my side. I'm sorry.

Regarding topic: The VTX you have is an Eachine XF5804. We have this VTX in this repo. Please download the table and load it in Betaflight first.

**Comment by ermakin** [comment]
XF5804 PRO FPV Video Transmitter 5.8G 48CH
25mW/200mW/600mW Switchable OSD Adjustable
MMCX VTX
A
b
C
d
E
CH
CH1 CH2 С3 CH4 CH5 CH6 CH7 CH8
FR
000000‹
0 0 0 5865 5845 5825 5805 5785 5765 5745 5725
05733 5752 5711 5790 5809 5828 5847 5866
5705 5685 5665 5665 5885 5905 5905 5905
• 5740 5760 5780 5800 5820 5840 5860 5880
5658 5695 5732 5769 5806 5843 5880 5917
