### ISSUE TITLE
Rush Tank Mini & Pro

### ISSUE THREAD

**Issue by RadianceNL** [Jackjan4/betaflight-vtx-tables#4]
Here's my VTX table for the Rush Tank Mini and Rush Tank Pro

# vtxtable
vtxtable bands 5
vtxtable channels 8
vtxtable band 1 BOSCAM_A A FACTORY 5865 5845 5825 5805 5785 5765 5745 5725
vtxtable band 2 BOSCAM_B B FACTORY 5733 5752 5771 5790 5809 5828 5847 5866
vtxtable band 3 BOSCAM_E E FACTORY 5705 5685 5665 5645 5885 5905 5925 5945
vtxtable band 4 FATSHARK F FACTORY 5740 5760 5780 5800 5820 5840 5860 5880
vtxtable band 5 RACEBAND R FACTORY 5658 5695 5732 5769 5806 5843 5880 5917
vtxtable powerlevels 4
vtxtable powervalues 14 23 27 29
vtxtable powerlabels 25 200 500 800

**Comment by seriousrob** [comment]
Please Change vtxtable powervalues line. The 37 has to be 27. 37dbm would be 5000mW.

**Comment by RadianceNL** [comment]
> Please Change vtxtable powervalues line. The 37 has to be 27. 37dbm would be 5000mW.

Must've been a typo. Thanks for the notification, I've corrected the value.

**Comment by Jackjan4** [comment]
Sorry for that long delay. I will add them.

**Comment by joevo2** [comment]
The official [VTX table](https://www.facebook.com/TEAM.RUSHFPV/posts/540316969885306?__xts__[0]=68.ARDYzt58qiYsYq9n5wqZZFd2btDU2fafb7z8oqN0HrmVhg-YDt3DJ4dADiLwBZbihOfH9HVx8Lh5XIluFB6mx25ouTal2RViRKO0GUolbVuHkHjHi4Gp4ZiYdIHDmPXXcqyFhrzkzv62S28KLngXeLCatU1Mt1Ngc1izzIxtlvMOwbIcy6ZZtad-BPljRNn5wNsKxwQg6n0jviw0MaYh1ZSY7sr-E2qshK5NDB19McuxrsF0EIIxqjS9DrSCOIS30nasnknGDC4nQYnk7R6xePOI_36VQpDgF8jkLrWy9ypU5xuiqgBkDSg5FnRglaTEMroMmqH5NVehlZaCVTE9eqY&__tn__=-R) provided by Rush
